package com.raphaowl.whiteowl.generator.name.tables;

import java.util.List;

public final class HumanNames {

    private HumanNames() {
    }

    public static final List<String> MALE_NAMES = List.of(
            "Aldric",
            "Alaric",
            "Aric",
            "Baldric",
            "Beren",
            "Brand",
            "Cedric",
            "Corwin",
            "Darian",
            "Duncan",
            "Edric",
            "Edwin",
            "Eldon",
            "Erik",
            "Falk",
            "Gareth",
            "Gavin",
            "Godric",
            "Hadrian",
            "Harold",
            "Jareth",
            "Kendrick",
            "Leoric",
            "Lucan",
            "Marcus",
            "Martin",
            "Mathias",
            "Nikolai",
            "Owen",
            "Percival",
            "Roland",
            "Roderick",
            "Stefan",
            "Theodore",
            "Thomas",
            "Tristan",
            "Ulric",
            "Victor",
            "Vincent",
            "Walter",
            "William",
            "Cedan",
            "Brom",
            "Edgar",
            "Hector",
            "Osric",
            "Ronan",
            "Silas",
            "Tobias",
            "Viggo"
    );

    public static final List<String> FEMALE_NAMES = List.of(
            "Adelaide",
            "Agnes",
            "Alice",
            "Alina",
            "Amelia",
            "Annika",
            "Beatrice",
            "Brienne",
            "Catherine",
            "Celeste",
            "Clara",
            "Diana",
            "Edith",
            "Eleanor",
            "Elena",
            "Elisa",
            "Emma",
            "Evelyn",
            "Fiona",
            "Freya",
            "Genevieve",
            "Grace",
            "Helena",
            "Isabella",
            "Juliana",
            "Katherine",
            "Lillian",
            "Lucille",
            "Lydia",
            "Margaret",
            "Marianne",
            "Matilda",
            "Miriam",
            "Natalia",
            "Olivia",
            "Penelope",
            "Rosalind",
            "Rowena",
            "Sarah",
            "Sophia",
            "Sylvia",
            "Teresa",
            "Valerie",
            "Victoria",
            "Vivian",
            "Willow",
            "Yvette",
            "Zara",
            "Astrid",
            "Meredith"
    );

    public static final List<String> TITLES = List.of(
            "O Bravo",
            "O Destemido",
            "O Errante",
            "O Mercador",
            "O Ferreiro",
            "O Caçador",
            "O Escudeiro",
            "O Veterano",
            "O Vigilante",
            "O Peregrino",
            "O Sobrevivente",
            "O Protetor",
            "O Andarilho",
            "O Explorador",
            "O Sábio",
            "O Implacável",
            "O Leal",
            "O Justo",
            "O Intrépido",
            "O Resoluto"
    );

}